disabled_rules:
 - cyclomatic_complexity
 - colon
 - function_body_length
 - no_space_in_method_call
 - todo
 - force_cast
 - identifier_name
 - shorthand_operator
 - type_name
 - implicit_getter
 - unused_optional_binding
 - multiple_closures_with_trailing_closure
 - unused_setter_value
 - operator_whitespace
 - weak_delegate

excluded:
 - test

line_length: 600
type_body_length:
  - 500
  - 800
file_length:
  warning: 99999
  error: 999999
type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
reporter: "xcode"
