using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to EmployeeSession resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class EmployeeSessionRepository : RepositoryBase<EmployeeSession>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public EmployeeSessionRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("EmployeeSessionRepository");
        }

        /// <summary>
        /// Fetches multiple EmployeeSessions
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<EmployeeSession>>>> FetchEmployeeSessions(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<EmployeeSession>("SELECT * FROM \"EmployeeSession\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<EmployeeSession>>.None);
                    }

                    return Result.Ok(Maybe<List<EmployeeSession>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<EmployeeSession>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple EmployeeSessions
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<EmployeeSession>>>> FetchCountedEmployeeSessions(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"EmployeeSession\"; SELECT * FROM \"EmployeeSession\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<EmployeeSession>().ToList();

                    var paginatedData = new PaginatedResult<EmployeeSession> {
                      Data = data ?? new List<EmployeeSession>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<EmployeeSession>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<EmployeeSession>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single EmployeeSession
        /// </summary>
        /// <param name="resourceId">The id of the EmployeeSession you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<EmployeeSession>>> FetchEmployeeSession(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<EmployeeSession>("SELECT * FROM \"EmployeeSession\" WHERE sessionId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<EmployeeSession>.None);
                    }

                    return Result.Ok(Maybe<EmployeeSession>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<EmployeeSession>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new EmployeeSession
        /// </summary>
        /// <param name="newEmployeeSession">The EmployeeSession to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateEmployeeSession(EmployeeSession newEmployeeSession)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""EmployeeSession""(
                            
                            employeeId,
                            authToken,
                            refreshToken,
                            expiry,
                            refreshExpiry
                        ) VALUES (
                            
                            @EmployeeId,
                            @AuthToken,
                            @RefreshToken,
                            @Expiry,
                            @RefreshExpiry
                        ) RETURNING sessionId",
                        newEmployeeSession
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single EmployeeSession
        /// </summary>
        /// <param name="resourceId">The id of the EmployeeSession you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropEmployeeSession(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"EmployeeSession\" WHERE sessionId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single EmployeeSession with a new full set of values
        /// </summary>
        /// <param name="replacedEmployeeSession">The new data for the EmployeeSession you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceEmployeeSession(EmployeeSession replacedEmployeeSession)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""EmployeeSession""
                        SET
                        sessionId = @SessionId,
                        employeeId = @EmployeeId,
                        authToken = @AuthToken,
                        refreshToken = @RefreshToken,
                        expiry = @Expiry,
                        refreshExpiry = @RefreshExpiry
                        WHERE sessionId = @EmployeeSessionId",
                        replacedEmployeeSession
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single EmployeeSession with one or more values
        /// </summary>
        /// <param name="updatedEmployeeSession">The new data for the EmployeeSession you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateEmployeeSession(EmployeeSessionPatch updatedEmployeeSession)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedEmployeeSession;
                    var operationCount = 0;

                    if (obj.SessionId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.SessionId.Operation == OperationKind.Remove 
                            ? "sessionId = NULL,"
                            : "sessionId = @SessionId,"
                        );
                        operationCount++;
                    }
                    if (obj.EmployeeId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.EmployeeId.Operation == OperationKind.Remove 
                            ? "employeeId = NULL,"
                            : "employeeId = @EmployeeId,"
                        );
                        operationCount++;
                    }
                    if (obj.AuthToken != null)
                    {
                        sqlPatchOperations.AppendLine(obj.AuthToken.Operation == OperationKind.Remove 
                            ? "authToken = NULL,"
                            : "authToken = @AuthToken,"
                        );
                        operationCount++;
                    }
                    if (obj.RefreshToken != null)
                    {
                        sqlPatchOperations.AppendLine(obj.RefreshToken.Operation == OperationKind.Remove 
                            ? "refreshToken = NULL,"
                            : "refreshToken = @RefreshToken,"
                        );
                        operationCount++;
                    }
                    if (obj.Expiry != null)
                    {
                        sqlPatchOperations.AppendLine(obj.Expiry.Operation == OperationKind.Remove 
                            ? "expiry = NULL,"
                            : "expiry = @Expiry,"
                        );
                        operationCount++;
                    }
                    if (obj.RefreshExpiry != null)
                    {
                        sqlPatchOperations.AppendLine(obj.RefreshExpiry.Operation == OperationKind.Remove 
                            ? "refreshExpiry = NULL,"
                            : "refreshExpiry = @RefreshExpiry,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"EmployeeSession\" SET {patchOperations} WHERE sessionId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        SessionId = (int) (obj.SessionId == default ? default : obj.SessionId.Value),
                        EmployeeId = (int) (obj.EmployeeId == default ? default : obj.EmployeeId.Value),
                        AuthToken = (string) (obj.AuthToken == default ? default : obj.AuthToken.Value),
                        RefreshToken = (string) (obj.RefreshToken == default ? default : obj.RefreshToken.Value),
                        Expiry = (DateTime) (obj.Expiry == default ? default : obj.Expiry.Value),
                        RefreshExpiry = (DateTime) (obj.RefreshExpiry == default ? default : obj.RefreshExpiry.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
