using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to Image resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class ImageRepository : RepositoryBase<Image>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public ImageRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("ImageRepository");
        }

        /// <summary>
        /// Fetches multiple Images
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<Image>>>> FetchImages(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<Image>("SELECT * FROM \"Image\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<Image>>.None);
                    }

                    return Result.Ok(Maybe<List<Image>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<Image>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple Images
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<Image>>>> FetchCountedImages(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"Image\"; SELECT * FROM \"Image\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<Image>().ToList();

                    var paginatedData = new PaginatedResult<Image> {
                      Data = data ?? new List<Image>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<Image>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<Image>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single Image
        /// </summary>
        /// <param name="resourceId">The id of the Image you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<Image>>> FetchImage(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<Image>("SELECT * FROM \"Image\" WHERE imageId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<Image>.None);
                    }

                    return Result.Ok(Maybe<Image>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<Image>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new Image
        /// </summary>
        /// <param name="newImage">The Image to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateImage(Image newImage)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""Image""(
                            companyId,
                            imageKey,
                            imageTitle
                        ) VALUES (
                            @CompanyId,
                            @ImageKey,
                            @ImageTitle
                        ) RETURNING imageId",
                        newImage
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single Image
        /// </summary>
        /// <param name="resourceId">The id of the Image you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropImage(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"Image\" WHERE imageId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single Image with a new full set of values
        /// </summary>
        /// <param name="replacedImage">The new data for the Image you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceImage(Image replacedImage)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""Image""
                        SET
                        companyId = @CompanyId,
                        imageKey = @ImageKey,
                        imageTitle = @ImageTitle
                        WHERE imageId = @ImageId",
                        replacedImage
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single Image with one or more values
        /// </summary>
        /// <param name="updatedImage">The new data for the Image you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateImage(ImagePatch updatedImage)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedImage;
                    var operationCount = 0;

                    if (obj.CompanyId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.CompanyId.Operation == OperationKind.Remove 
                            ? "companyId = NULL,"
                            : "companyId = @CompanyId,"
                        );
                        operationCount++;
                    }
                    if (obj.ImageKey != null)
                    {
                        sqlPatchOperations.AppendLine(obj.ImageKey.Operation == OperationKind.Remove 
                            ? "imageKey = NULL,"
                            : "imageKey = @ImageKey,"
                        );
                        operationCount++;
                    }
                    if (obj.ImageTitle != null)
                    {
                        sqlPatchOperations.AppendLine(obj.ImageTitle.Operation == OperationKind.Remove 
                            ? "imageTitle = NULL,"
                            : "imageTitle = @ImageTitle,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"Image\" SET {patchOperations} WHERE imageId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        CompanyId = (int) (obj.CompanyId == default ? default : obj.CompanyId.Value),
                        ImageKey = (string) (obj.ImageKey == default ? default : obj.ImageKey.Value),
                        ImageTitle = (string) (obj.ImageTitle == default ? default : obj.ImageTitle.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
