using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to Menu resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class MenuRepository : RepositoryBase<Menu>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public MenuRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("MenuRepository");
        }

        /// <summary>
        /// Fetches multiple Menus
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<Menu>>>> FetchMenus(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<Menu>("SELECT * FROM \"Menu\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<Menu>>.None);
                    }

                    return Result.Ok(Maybe<List<Menu>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<Menu>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple Menus
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<Menu>>>> FetchCountedMenus(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"Menu\"; SELECT * FROM \"Menu\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<Menu>().ToList();

                    var paginatedData = new PaginatedResult<Menu> {
                      Data = data ?? new List<Menu>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<Menu>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<Menu>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single Menu
        /// </summary>
        /// <param name="resourceId">The id of the Menu you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<Menu>>> FetchMenu(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<Menu>("SELECT * FROM \"Menu\" WHERE menuId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<Menu>.None);
                    }

                    return Result.Ok(Maybe<Menu>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<Menu>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new Menu
        /// </summary>
        /// <param name="newMenu">The Menu to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateMenu(Menu newMenu)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""Menu""(
                            venueId,
                            menuDescription,
                            menuName,
                            menuImage
                        ) VALUES (
                            @VenueId,
                            @MenuDescription,
                            @MenuName,
                            @MenuImage
                        ) RETURNING menuId",
                        newMenu
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single Menu
        /// </summary>
        /// <param name="resourceId">The id of the Menu you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropMenu(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"Menu\" WHERE menuId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single Menu with a new full set of values
        /// </summary>
        /// <param name="replacedMenu">The new data for the Menu you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceMenu(Menu replacedMenu)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""Menu""
                        SET
                        venueId = @VenueId,
                        menuDescription = @MenuDescription,
                        menuName = @MenuName,
                        menuImage = @MenuImage
                        WHERE menuId = @MenuId",
                        replacedMenu
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single Menu with one or more values
        /// </summary>
        /// <param name="updatedMenu">The new data for the Menu you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateMenu(MenuPatch updatedMenu)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedMenu;
                    var operationCount = 0;

                    if (obj.VenueId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.VenueId.Operation == OperationKind.Remove 
                            ? "venueId = NULL,"
                            : "venueId = @VenueId,"
                        );
                        operationCount++;
                    }
                    if (obj.MenuDescription != null)
                    {
                        sqlPatchOperations.AppendLine(obj.MenuDescription.Operation == OperationKind.Remove 
                            ? "menuDescription = NULL,"
                            : "menuDescription = @MenuDescription,"
                        );
                        operationCount++;
                    }
                    if (obj.MenuName != null)
                    {
                        sqlPatchOperations.AppendLine(obj.MenuName.Operation == OperationKind.Remove 
                            ? "menuName = NULL,"
                            : "menuName = @MenuName,"
                        );
                        operationCount++;
                    }
                    if (obj.MenuImage != null)
                    {
                        sqlPatchOperations.AppendLine(obj.MenuImage.Operation == OperationKind.Remove 
                            ? "menuImage = NULL,"
                            : "menuImage = @MenuImage,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"Menu\" SET {patchOperations} WHERE menuId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        VenueId = (int) (obj.VenueId == default ? default : obj.VenueId.Value),
                        MenuDescription = (string) (obj.MenuDescription == default ? default : obj.MenuDescription.Value),
                        MenuName = (string) (obj.MenuName == default ? default : obj.MenuName.Value),
                        MenuImage = (string) (obj.MenuImage == default ? default : obj.MenuImage.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
