using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to OrderLine resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class OrderLineRepository : RepositoryBase<OrderLine>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public OrderLineRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("OrderLineRepository");
        }

        /// <summary>
        /// Fetches multiple OrderLines
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<OrderLine>>>> FetchOrderLines(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<OrderLine>("SELECT * FROM \"OrderLine\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<OrderLine>>.None);
                    }

                    return Result.Ok(Maybe<List<OrderLine>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<OrderLine>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple OrderLines
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<OrderLine>>>> FetchCountedOrderLines(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"OrderLine\"; SELECT * FROM \"OrderLine\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<OrderLine>().ToList();

                    var paginatedData = new PaginatedResult<OrderLine> {
                      Data = data ?? new List<OrderLine>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<OrderLine>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<OrderLine>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single OrderLine
        /// </summary>
        /// <param name="resourceId">The id of the OrderLine you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<OrderLine>>> FetchOrderLine(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<OrderLine>("SELECT * FROM \"OrderLine\" WHERE orderLineId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<OrderLine>.None);
                    }

                    return Result.Ok(Maybe<OrderLine>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<OrderLine>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new OrderLine
        /// </summary>
        /// <param name="newOrderLine">The OrderLine to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateOrderLine(OrderLine newOrderLine)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""OrderLine""(
                            orderId,
                            productId,
                            quantity,
                            amount
                        ) VALUES (
                            @OrderId,
                            @ProductId,
                            @Quantity,
                            @Amount
                        ) RETURNING orderLineId",
                        newOrderLine
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single OrderLine
        /// </summary>
        /// <param name="resourceId">The id of the OrderLine you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropOrderLine(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"OrderLine\" WHERE orderLineId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single OrderLine with a new full set of values
        /// </summary>
        /// <param name="replacedOrderLine">The new data for the OrderLine you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceOrderLine(OrderLine replacedOrderLine)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""OrderLine""
                        SET
                        orderId = @OrderId,
                        productId = @ProductId,
                        quantity = @Quantity,
                        amount = @Amount
                        WHERE orderLineId = @OrderLineId",
                        replacedOrderLine
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single OrderLine with one or more values
        /// </summary>
        /// <param name="updatedOrderLine">The new data for the OrderLine you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateOrderLine(OrderLinePatch updatedOrderLine)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedOrderLine;
                    var operationCount = 0;

                    if (obj.OrderId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.OrderId.Operation == OperationKind.Remove 
                            ? "orderId = NULL,"
                            : "orderId = @OrderId,"
                        );
                        operationCount++;
                    }
                    if (obj.ProductId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.ProductId.Operation == OperationKind.Remove 
                            ? "productId = NULL,"
                            : "productId = @ProductId,"
                        );
                        operationCount++;
                    }
                    if (obj.Quantity != null)
                    {
                        sqlPatchOperations.AppendLine(obj.Quantity.Operation == OperationKind.Remove 
                            ? "quantity = NULL,"
                            : "quantity = @Quantity,"
                        );
                        operationCount++;
                    }
                    if (obj.Amount != null)
                    {
                        sqlPatchOperations.AppendLine(obj.Amount.Operation == OperationKind.Remove 
                            ? "amount = NULL,"
                            : "amount = @Amount,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"OrderLine\" SET {patchOperations} WHERE orderLineId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        OrderId = (int) (obj.OrderId == default ? default : obj.OrderId.Value),
                        ProductId = (int) (obj.ProductId == default ? default : obj.ProductId.Value),
                        Quantity = (int) (obj.Quantity == default ? default : obj.Quantity.Value),
                        Amount = (decimal) (obj.Amount == default ? default : obj.Amount.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
