using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to ProductType resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class ProductTypeRepository : RepositoryBase<ProductType>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public ProductTypeRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("ProductTypeRepository");
        }

        /// <summary>
        /// Fetches multiple ProductTypes
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<ProductType>>>> FetchProductTypes(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<ProductType>("SELECT * FROM \"ProductType\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<ProductType>>.None);
                    }

                    return Result.Ok(Maybe<List<ProductType>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<ProductType>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple ProductTypes
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<ProductType>>>> FetchCountedProductTypes(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"ProductType\"; SELECT * FROM \"ProductType\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<ProductType>().ToList();

                    var paginatedData = new PaginatedResult<ProductType> {
                      Data = data ?? new List<ProductType>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<ProductType>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<ProductType>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single ProductType
        /// </summary>
        /// <param name="resourceId">The id of the ProductType you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<ProductType>>> FetchProductType(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<ProductType>("SELECT * FROM \"ProductType\" WHERE productTypeId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<ProductType>.None);
                    }

                    return Result.Ok(Maybe<ProductType>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<ProductType>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new ProductType
        /// </summary>
        /// <param name="newProductType">The ProductType to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateProductType(ProductType newProductType)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""ProductType""(
                            productTypeName
                        ) VALUES (
                            @ProductTypeName
                        ) RETURNING productTypeId",
                        newProductType
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single ProductType
        /// </summary>
        /// <param name="resourceId">The id of the ProductType you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropProductType(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"ProductType\" WHERE productTypeId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single ProductType with a new full set of values
        /// </summary>
        /// <param name="replacedProductType">The new data for the ProductType you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceProductType(ProductType replacedProductType)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""ProductType""
                        SET
                        productTypeName = @ProductTypeName
                        WHERE productTypeId = @ProductTypeId",
                        replacedProductType
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single ProductType with one or more values
        /// </summary>
        /// <param name="updatedProductType">The new data for the ProductType you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateProductType(ProductTypePatch updatedProductType)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedProductType;
                    var operationCount = 0;

                    if (obj.ProductTypeName != null)
                    {
                        sqlPatchOperations.AppendLine(obj.ProductTypeName.Operation == OperationKind.Remove 
                            ? "productTypeName = NULL,"
                            : "productTypeName = @ProductTypeName,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"ProductType\" SET {patchOperations} WHERE productTypeId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        ProductTypeName = (string) (obj.ProductTypeName == default ? default : obj.ProductTypeName.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
