using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using CSharpFunctionalExtensions;
using Dapper;
using Koasta.Shared.Configuration;
using Koasta.Shared.Models;
using Koasta.Shared.PatchModels;
using Koasta.Shared.Types;
using System.Text;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

// WARNING: This file is auto-generated from {repository root}/scripts/csport/generate-repositories.js.
//          Do not edit this file directly, as changes will be replaced!

namespace Koasta.Shared.Database
{
    /*
    A repository for data access to VenueOpeningTime resources.
    */
    [CompilerGeneratedAttribute()]
    public partial class VenueOpeningTimeRepository : RepositoryBase<VenueOpeningTime>
    {
        private readonly ISettings settings;
        private readonly ILogger logger;

        public VenueOpeningTimeRepository(ISettings settings, ILoggerFactory logger) : base()
        {
            this.settings = settings;
            this.logger = logger.CreateLogger("VenueOpeningTimeRepository");
        }

        /// <summary>
        /// Fetches multiple VenueOpeningTimes
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<List<VenueOpeningTime>>>> FetchVenueOpeningTimes(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<VenueOpeningTime>("SELECT * FROM \"VenueOpeningTime\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false)).ToList();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<List<VenueOpeningTime>>.None);
                    }

                    return Result.Ok(Maybe<List<VenueOpeningTime>>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<List<VenueOpeningTime>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches multiple VenueOpeningTimes
        /// </summary>
        /// <param name="page">The current page number</param>
        /// <param name="count">The page size</param>
        /// <returns>Returns a result containing an optional list of items</returns>
        public async Task<Result<Maybe<PaginatedResult<VenueOpeningTime>>>> FetchCountedVenueOpeningTimes(int page, int count)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    using var obj = await con.QueryMultipleAsync("SELECT COUNT(*) FROM \"VenueOpeningTime\"; SELECT * FROM \"VenueOpeningTime\" LIMIT @Limit OFFSET @Offset", new { Limit = count, Offset = page * count }).ConfigureAwait(false);
                    var totalCount = obj.Read<int>().Single();
                    var data = obj.Read<VenueOpeningTime>().ToList();

                    var paginatedData = new PaginatedResult<VenueOpeningTime> {
                      Data = data ?? new List<VenueOpeningTime>(),
                      Count = totalCount
                    };

                    return Result.Ok(Maybe<PaginatedResult<VenueOpeningTime>>.From(paginatedData));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<PaginatedResult<VenueOpeningTime>>>(ex.ToString());
            }
        }

        /// <summary>
        /// Fetches a single VenueOpeningTime
        /// </summary>
        /// <param name="resourceId">The id of the VenueOpeningTime you wish to fetch</param>
        /// <returns>Returns a result containing an optional item</returns>
        public async Task<Result<Maybe<VenueOpeningTime>>> FetchVenueOpeningTime(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<VenueOpeningTime>("SELECT * FROM \"VenueOpeningTime\" WHERE venueOpeningTimeId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false)).FirstOrDefault();
                    if (data == null)
                    {
                        return Result.Ok(Maybe<VenueOpeningTime>.None);
                    }

                    return Result.Ok(Maybe<VenueOpeningTime>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<VenueOpeningTime>>(ex.ToString());
            }
        }

        /// <summary>
        /// Inserts a new VenueOpeningTime
        /// </summary>
        /// <param name="newVenueOpeningTime">The VenueOpeningTime to be inserted</param>
        /// <returns>Returns a result containing the created resource id</returns>
        public async Task<Result<Maybe<int>>> CreateVenueOpeningTime(VenueOpeningTime newVenueOpeningTime)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var data = (await con.QueryAsync<int>(
                        @"INSERT INTO ""VenueOpeningTime""(
                            venueId,
                            startTime,
                            endTime,
                            dayOfWeek
                        ) VALUES (
                            @VenueId,
                            @StartTime,
                            @EndTime,
                            @DayOfWeek
                        ) RETURNING venueOpeningTimeId",
                        newVenueOpeningTime
                    ).ConfigureAwait(false)).FirstOrDefault();
                    if (data < 1)
                    {
                        return Result.Ok(Maybe<int>.None);
                    }

                    return Result.Ok(Maybe<int>.From(data));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail<Maybe<int>>(ex.ToString());
            }
        }

        /// <summary>
        /// Deletes a single VenueOpeningTime
        /// </summary>
        /// <param name="resourceId">The id of the VenueOpeningTime you wish to delete</param>
        /// <returns>Returns a result indicating if the delete succeeded</returns>
        public async Task<Result> DropVenueOpeningTime(int resourceId)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync("DELETE FROM \"VenueOpeningTime\" WHERE venueOpeningTimeId = @ResourceId", new { ResourceId = resourceId }).ConfigureAwait(false);
                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Replaces a single VenueOpeningTime with a new full set of values
        /// </summary>
        /// <param name="replacedVenueOpeningTime">The new data for the VenueOpeningTime you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> ReplaceVenueOpeningTime(VenueOpeningTime replacedVenueOpeningTime)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    await con.ExecuteAsync(
                        @"UPDATE ""VenueOpeningTime""
                        SET
                        venueId = @VenueId,
                        startTime = @StartTime,
                        endTime = @EndTime,
                        dayOfWeek = @DayOfWeek
                        WHERE venueOpeningTimeId = @VenueOpeningTimeId",
                        replacedVenueOpeningTime
                    ).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }

        /// <summary>
        /// Updates a single VenueOpeningTime with one or more values
        /// </summary>
        /// <param name="updatedVenueOpeningTime">The new data for the VenueOpeningTime you wish to update</param>
        /// <returns>Returns a result indicating if the operation succeeded</returns>
        public async Task<Result> UpdateVenueOpeningTime(VenueOpeningTimePatch updatedVenueOpeningTime)
        {
            try
            {
                using (var con = new Npgsql.NpgsqlConnection(settings.Connection.DatabaseConnectionString))
                {
                    var sqlPatchOperations = new StringBuilder();
                    var obj = updatedVenueOpeningTime;
                    var operationCount = 0;

                    if (obj.VenueId != null)
                    {
                        sqlPatchOperations.AppendLine(obj.VenueId.Operation == OperationKind.Remove 
                            ? "venueId = NULL,"
                            : "venueId = @VenueId,"
                        );
                        operationCount++;
                    }
                    if (obj.StartTime != null)
                    {
                        sqlPatchOperations.AppendLine(obj.StartTime.Operation == OperationKind.Remove 
                            ? "startTime = NULL,"
                            : "startTime = @StartTime,"
                        );
                        operationCount++;
                    }
                    if (obj.EndTime != null)
                    {
                        sqlPatchOperations.AppendLine(obj.EndTime.Operation == OperationKind.Remove 
                            ? "endTime = NULL,"
                            : "endTime = @EndTime,"
                        );
                        operationCount++;
                    }
                    if (obj.DayOfWeek != null)
                    {
                        sqlPatchOperations.AppendLine(obj.DayOfWeek.Operation == OperationKind.Remove 
                            ? "dayOfWeek = NULL,"
                            : "dayOfWeek = @DayOfWeek,"
                        );
                        operationCount++;
                    }

                    var patchOperations = sqlPatchOperations.ToString();

                    if (operationCount > 0)
                    {
                        // Remove final ", " from StringBuilder to ensure query is valid
                        patchOperations = patchOperations.TrimEnd(System.Environment.NewLine.ToCharArray());
                        patchOperations = patchOperations.TrimEnd(',');
                    }

                    await con.ExecuteAsync($"UPDATE \"VenueOpeningTime\" SET {patchOperations} WHERE venueOpeningTimeId = @ResourceId", new {
                        ResourceId = obj.ResourceId,
                        VenueId = (int) (obj.VenueId == default ? default : obj.VenueId.Value),
                        StartTime = (TimeSpan) (obj.StartTime == default ? default : obj.StartTime.Value),
                        EndTime = (TimeSpan) (obj.EndTime == default ? default : obj.EndTime.Value),
                        DayOfWeek = (int) (obj.DayOfWeek == default ? default : obj.DayOfWeek.Value)
                    }).ConfigureAwait(false);

                    return Result.Ok();
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Query failed");
                return Result.Fail(ex.ToString());
            }
        }
    }
}
