ALTER TABLE "Venue" ADD COLUMN servingType INT NOT NULL DEFAULT 0;
ALTER TABLE "CustomerOrder" ADD COLUMN servingType INT NOT NULL DEFAULT 0;
ALTER TABLE "CustomerOrder" ADD COLUMN tableName VARCHAR(30) NULL;
